== Jersey Header propagation from Property and Environment

This lets the user configure environment variables to propagate across calls. It will check if they
are there on incoming calls and if so, add then to its own logging context so they are logged.

When the calls go out, it will check if the given names exist in the logging context, and if so, add them
as the required headers. If not, it will attempt to take the environment variables it knows about and send those.

The fields are:

connect.logging.headers.from-environment=MY_KUBE_NODE=X-Origin-Kube-Node,MY_KUBE_REGION=X-Origin-Kube-Region

This will on first node that doesn't have that header cause it to add the value of those environment variables into
the logging context as origin.kube.node and origin.kube.region (- change to ., everything is lower cased).

If the next server sees that header, it will just pick it up, add it to the logging context and send it on.

connect.logging.headers.from-properties=my.property.name=X-Property-Name

Does the same for system properties.

NOTE: *This bypasses the logging filter that only propagates known headers* if this is installed and configured. The
two lists should be kept separate as that only propagates headers it knows.



