= Connect App Config

This is a lightweight version of StickyCode and is opinionated about how configuration works. It is intended
to allow you to grab your configuration easily by annotating your properties, just like in StickyCode, but:
 
- you must reach out and ask, it is therefore not limited to beans 
- it doesn't just inject the config once, it will do it every time a bean is created and will limit itself to  just
  that bean
- it doesn't when asked not part of the bean lifecycle. So it can be requested in the construction of the bean. This
allows you to have your configuration up front.
- it only allows the use of system properties as configuration (I said it was opinionated!)

=== Phases 

StickyCode has two distinct phases - wiring vs configuration. It has an outstanding issue that the order of 
configuration does not follow the order of wiring, so you can end up trying to do configuration operations when
the bean you are depending on has itself not been configured. Although the two phases are a great idea, Sticky
has to go through hoops to achieve this and adapters have to be written for each DI framework. This simple mechanism
avoids this and makes it DI agnostic.

So no phases


=== Use

The libraries currently hold onto all bean classes that are being configured but that may change in the future. Stickycode
has a few extra functions - such as postconfigured and pre-start annotations that might be useful.

a bean could look like this:

----
public class Sample1 {
  @ConfigKey("sample1.value")
  private String value;
  @ConfigKey("sample1.value2")
  private Integer value2;
  @ConfigKey("sample1.value3")
  private List<String> value3;
  @ConfigKey("sample1.value4")
  private Map<String,String> value4;
  @ConfigKey("sample1.dontneed-to-provide-value-for-as-has-default")
  private String alreadyDefault = "default";
  
  public Sample1() {
    DeclaredConfigResolver.resolve(this);
  }
}
----

If any of the config is missing, it will throw a MissingConfiguration exception. A config for this would look like:

----
sampe1.value=A string
sample1.value2=10
# don't use spaces, they get included, so one, two ==> ["one", " two"]
sample1.value3=one,two,three
# i override the default map coercian, so these get trimmed
sample1.value4=one=two,three = four
----

=== Thanks

To Michael McCallum for writing stickycode - it is awesome, but i always find myself adapting it. I have to say
the propensity to use private injectors made it more difficult this time!


   
