== Jersey Common

This is just a bunch of common jersey functionality we seem to use in all our Jersey based apps. In some
cases it is just enabling things that exist in other libraries for convenience, in some cases its resources
we otherwise create time and again (health, prometheus).

All dependencies are `provided` so that you don't have to use them all or can provide your own versions of
them if necessary.

==== CommonConfiguration

This enables:

- Jackson for JSON parsing in Jersey
- MultiPart Form support
- GZIP support
- Adds in a jackson Mapper so that everything across the board (client and server) is using the same
Mapping configuration.
- A default exception mapper so that non-`WebApplicationException`s get logged and dealt with.

requires: (core jersey) jersey-media-json-jackson, jersey-media-multipart, jersey-common

==== LoggingConfiguration

This enables:

- Client and Server side logging of payloads. You can decide on the ones you wish to turn off, such
as health checks, metrics and password ones.

requires: connect-java-logging (it augments the log)

==== InfrastructureConfiguration

This enable:

- Prometheus Metrics
- Prometheus dynamic Jersey wrapper that keeps track of performance
- Health

requires: connect-prometheus-jersey:2.2+, prometheus' simpleclient java library:0.0.23+