== Connect Vault Initializer

If included and you are using the Bathe/Spring Loaded packager, then this initializer will
run immediately after the system properties are loaded and look for any system properties with
the prefix of [K8SVAULT] (case sensitive).

It will strip that off and take the rest as a key for pulling secrets from Vault.

It will connect to vault using the environment:

- *VAULT_URL* - this is the url of the Vault server. This must be provided.
- *VAULT_TOKENFILE* - the location of the JWT token file. This defaults to `/var/run/secrets/kubernetes.io/serviceaccount/token`.
- *VAULT_CERTFILE* - the location of the PEM config. This defaults to `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.
- *VAULT_ROLE* - if this is provided, the client will attempt to login with its JWT to get an Auth JWT first
- *VAULT_ROLE_URL* - the location of Auth endpoint if the VAULT_ROLE has been provided. Default si `/v1/auth/kubernetes/login`.

It will create a bunch of requests in parallel to get its configuration as quickly as possible.

NOTE: It fails quickly - if anything is wrong, it kills the process with the appropriate errors.
